fll/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pit/', include('pit.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home')
]

pit/urls.py
from django.urls import path

from . import views

app_name = 'pit'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('recursos/', views.recursos, name='recursos'),
    path('horario/<int:sala>/', views.horario, name='horario'),
    path('actualizarhorario/', views.actualizar_horario, name='actualizarhorario'),
    path('confirmarhorario/', views.confirmar_horario, name='confirmarhorario'),
    path('horariocompleto/<int:sala>/', views.horario_futuro_completo, name='horariocompleto'),
    path('horariopasado/<int:sala>/', views.horario_pasado, name='horariopasado'),
    path('horario1080/<int:sala>/', views.horario_1080, name='horario1080'),
    path('horariostatic/<int:sala>/', views.horario_static, name='horariostatic')
]

pit/models.py
from django.db import models

class Sala(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre

class Equipo(models.Model):
    nombre = models.CharField(max_length=50, unique=True)
    idequipo = models.IntegerField(unique=True)
    salapreferible = models.ForeignKey(Sala, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('nombre', 'idequipo'),)

    def __str__(self):
        return "{} - {}".format(self.idequipo, self.nombre)

class Mesa(models.Model):
    nombre = models.CharField(max_length=4, unique=True)
    sala = models.ForeignKey(Sala, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class Slot(models.Model):
    horainicio = models.TimeField()
    horafin = models.TimeField()

    class Meta:
        unique_together = (('horainicio', 'horafin'),)

    def __str__(self):
        return self.horainicio.strftime("%-H:%M") + "-" + self.horafin.strftime("%-H:%M")


class Reserva(models.Model):
    slot = models.ForeignKey(Slot, on_delete=models.CASCADE)
    mesa = models.ForeignKey(Mesa, on_delete=models.CASCADE)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('slot', 'mesa'),)

    def __str__(self):
        return 'Equipo "{}" en la mesa {}, slot {}'.format(self.equipo, self.mesa, self.slot)

class EnlacesExtra(models.Model):
    enlace = models.URLField(max_length=200)
    texto = models.CharField(max_length=50)

    def __str__(self):
        return self.texto

pit/views.py
from datetime import datetime, timedelta
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.views.decorators.cache import never_cache
from .models import Equipo, Mesa, Slot, Reserva, Sala, EnlacesExtra

class IndexView(generic.ListView):
    template_name = 'pit/index.html'
    context_object_name = 'datos'

    def get_queryset(self):
        #Reservas es (slot, mesa): equipo
        reservas = dict()
        for i in Reserva.objects.all():
            if i.slot.id not in reservas:
                reservas[i.slot.id] = dict()
            reservas[i.slot.id][i.mesa.id] = i.equipo

        return {
            'mesas': Mesa.objects.all().order_by("nombre"),
            'slots': Slot.objects.filter(horafin__gte=datetime.now()).order_by("horainicio"),
            'equipos': Equipo.objects.all().order_by("idequipo"),
            'salas': Sala.objects.all().order_by("nombre"),
            'fechahoraservidor': datetime.now()
        }

def recursos(request):
    template = loader.get_template('pit/recursos.html')

    context = {
        'salas': Sala.objects.all().order_by("nombre"),
        'enlacesextra': EnlacesExtra.objects.all().order_by("-texto")
    }

    return HttpResponse(template.render(context, request))

# sala, sala a mostrar, 0 para todas
# numslots, número de slots a mostrar, 0 para no limitar
# direccion, 1 para mostrar el horario pasado (por defecto va hacia el futuro)
def _tabla_horario_futuro(sala, numslots, pasado=0):

    # Datos de DB necesarios
    salaobj = Sala.objects.filter(pk=sala)
    if pasado == 1:
        slots = Slot.objects.filter(horafin__lte=datetime.now()).order_by("horainicio")
    else:
        slots = Slot.objects.filter(horafin__gte=datetime.now()).order_by("horainicio")

    # Reservas es (slot, mesa): equipo
    reservas = dict()

    # Limitar el número de slots que se muestrana las numslots primeros
    if numslots > 0:
        slots = slots[:numslots]

    if salaobj.exists():
        nombresala = salaobj.first().nombre
        reservaobj = Reserva.objects.filter(mesa__sala=salaobj.first())
        for i in reservaobj:
            if i.slot.id not in reservas:
                reservas[i.slot.id] = dict()
            reservas[i.slot.id][i.mesa.id] = i.equipo.idequipo
        mesas = Mesa.objects.filter(sala=salaobj.first()).order_by("nombre")
    else:
        nombresala = 'PIT'
        reservaobj = Reserva.objects.all()
        for i in reservaobj:
            if i.slot.id not in reservas:
                reservas[i.slot.id] = dict()
            reservas[i.slot.id][i.mesa.id] = i.equipo.idequipo

        mesas = Mesa.objects.all().order_by("nombre")

    return mesas, slots, reservas, nombresala

@never_cache
def horario(request, sala):
    template = loader.get_template('pit/horario.html')

    # Se limita a 9 el máximo de registros a pintar
    mesas, slots, reservas, nombresala = _tabla_horario_futuro(sala, 9)

    context = {
        'mesas': mesas,
        'slots': slots,
        'reservas': reservas,
        'fechahoraactual': datetime.now(),
        'anchocol': str(75/len(mesas)).replace(',', '.'), #el 75 es porcentaje, la primera columna es 25 porque se establece en el html y el 75 porciento restante se reparte entre las demás
        'nombresala': nombresala
    }

    return HttpResponse(template.render(context, request))

@never_cache
def horario_1080(request, sala):
    template = loader.get_template('pit/horario1080.html')

    # Se limita a 9 el máximo de registros a pintar
    mesas, slots, reservas, nombresala =_tabla_horario_futuro(sala, 11)

    context = {
        'mesas': mesas,
        'slots': slots,
        'reservas': reservas,
        'fechahoraactual': datetime.now(),
        'anchocol': str(85/len(mesas)).replace(',', '.'), #el 85 es porcentaje, la primera columna es 15 porque se establece en el html y el 85 porciento restante se reparte entre las demás
        'nombresala': nombresala
    }

    return HttpResponse(template.render(context, request))

@never_cache
def horario_static(request, sala):
    template = loader.get_template('pit/horariostatic.html')

    # Se limita a 9 el máximo de registros a pintar
    mesas, slots, reservas, nombresala =_tabla_horario_futuro(sala, 0)

    context = {
        'mesas': mesas,
        'slots': slots,
        'reservas': reservas,
        'fechahoraactual': datetime.now(),
        'anchocol': str(85/len(mesas)).replace(',', '.'), #el 85 es porcentaje, la primera columna es 15 porque se establece en el html y el 85 porciento restante se reparte entre las demás
        'nombresala': nombresala,
        'salas': Sala.objects.all()
    }

    return HttpResponse(template.render(context, request))

def horario_futuro_completo(request, sala):
    template = loader.get_template('pit/horariofuturocompleto.html')

    # No se limita el máximo de registros a pintar
    mesas, slots, reservas, nombresala =_tabla_horario_futuro(sala, 0)

    context = {
        'mesas': mesas,
        'slots': slots,
        'reservas': reservas,
        'fechahoraactual': datetime.now(),
        'anchocol': str(75/len(mesas)).replace(',', '.'), #el 75 es porcentaje, la primera columna es 25 porque se establece en el html y el 75 porciento restante se reparte entre las demás
        'nombresala': nombresala
    }

    return HttpResponse(template.render(context, request))

def horario_pasado(request, sala):
    template = loader.get_template('pit/horariopasado.html')

    # No se limita el máximo de registros a pintar
    mesas, slots, reservas, nombresala =_tabla_horario_futuro(sala, 0, 1)

    context = {
        'mesas': mesas,
        'slots': slots,
        'reservas': reservas,
        'fechahoraactual': datetime.now(),
        'anchocol': str(75/len(mesas)).replace(',', '.'), #el 75 es porcentaje, la primera columna es 25 porque se establece en el html y el 75 porciento restante se reparte entre las demás
        'nombresala': nombresala
    }

    return HttpResponse(template.render(context, request))

def actualizar_horario(request):
    if request.method == 'GET':
        return HttpResponse(status=405)

    if request.method == 'POST':
        # Comprobar y leer campos de entrada
        if not all(x in request.POST for x in ['mesa', 'slot', 'equipo']):
            messages.error(request, "Falta campo en el formulario")
        mesa = int(request.POST['mesa'])
        slot = int(request.POST['slot'])
        equipo = int(request.POST['equipo'])

        # Obtener la info de base de datos
        mesaobj = Mesa.objects.filter(pk=mesa)
        slotobj = Slot.objects.filter(pk=slot)
        reserva_actual = Reserva.objects.filter(mesa=mesa, slot=slot)

        aviso_previo = ''

        # Liberar slot
        if equipo == -1:
            if reserva_actual.exists():
                mensaje = 'Se va a liberar el slot {} de la mesa {}, actualmente asignado al equipo "{}".'.format(slotobj.first(), mesaobj.first(), reserva_actual.first().equipo)
            else:
                mensaje = ''
                messages.info(request, 'El slot {} de la mesa {} está libre actualmente, no hay nada que cambiar nada.'.format(slotobj.first(), mesaobj.first()))
        # Asignar equipo
        else:
            pequipoobj = Equipo.objects.filter(pk=equipo).first()

            # Sala no preferida
            if pequipoobj.salapreferible.id != mesaobj.first().sala.id:
                aviso_previo += ' OjO: No se espera que el equipo reserve en esta sala, deberia reservar en {}.'.format(pequipoobj.salapreferible.nombre)

            # Ya hay slot reservado
            reserva_futura = Reserva.objects.filter(equipo=equipo, slot__horainicio__gte=datetime.now())
            if reserva_futura.exists():
                aviso_previo += ' OjO: El equipo ya tiene reserva en el slot {} de la mesa {}.'.format(reserva_futura.first().slot, reserva_futura.first().mesa)

            # El slot ya estaba ocupado
            if reserva_actual.exists():
                if pequipoobj.id == reserva_actual.first().equipo.id:
                    mensaje = ''
                    messages.info(request, 'El slot {} de la mesa {} ya estaba asignado al equipo "{}", no hay que cambiar nada.'.format(slotobj.first(), mesaobj.first(), pequipoobj))
                else:
                    aviso_previo += ' OjO: Ya hay un equipo ocupando este slot'
                    mensaje = 'Slot {} de la mesa {} actualmente asignado al equipo "{}", se va a reasignar al equipo "{}"'.format(reserva_actual.first(), reserva_actual.first().mesa, reserva_actual.first().equipo, pequipoobj)
            else:
                mensaje = 'Se va a asignar el slot {} de la mesa {} al equipo "{}"'.format(slotobj.first(), mesaobj.first(), pequipoobj)

        template = loader.get_template('pit/actualizarhorario.html')
        context = {
            'mesa': mesa,
            'slot': slot,
            'equipo': equipo,
            'mensaje': mensaje,
            'aviso_previo': aviso_previo
        }
        if mensaje == '':
            #Caso redundante, no hay nada que hacer
            return HttpResponseRedirect(reverse('pit:index'))
        else:
            return HttpResponse(template.render(context, request))

def confirmar_horario(request):
    if request.method == 'GET':
        return HttpResponse(status=405)

    if request.method == 'POST':
        if not all(x in request.POST for x in ['mesa', 'slot', 'equipo']):
            messages.error(request, "Falta campo en el formulario")

        mesa = int(request.POST['mesa'])
        slot = int(request.POST['slot'])
        equipo = int(request.POST['equipo'])

        if equipo == -1:
            Reserva.objects.filter(mesa=Mesa.objects.get(pk=mesa), slot=Slot.objects.get(pk=slot)).delete()
        else:
            Reserva.objects.update_or_create(

pit/templates/pit/actualizarhorario.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block imports %}
{% endblock imports %}

{% block content %}

<h1>Control de reservas de PIT - Confirmación</h1>
<form action="{% url 'pit:confirmarhorario' %}" method="post">
    <input type="hidden" name="slot" value="{{ slot }}">
    <input type="hidden" name="mesa" value="{{ mesa }}">
    <input type="hidden" name="equipo" value="{{ equipo }}">
    {% if aviso_previo %}<p style="color:red;font-weight:bold">{{ aviso_previo }}</p>{% endif %}
    <p>{{ mensaje }}</p>
    <p>¿Estás seguro?</p>
    {% csrf_token %}
    <input type="submit" value="Si">
    <button id="bno" type="button" value="No" onClick="window.location.href='/pit/';">No</button></p>
</form>

{% endblock content %}

pit/templates/pit/horario.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block metas %}
    <meta http-equiv="refresh" content="10">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
{% endblock metas %}

{% block bodytags %} class="horario"{% endblock %}

{% block content %}

<h1 class="horario">Reservas {{ nombresala }}</h1>
<table class="horariopublico">
    <tr><th style="width: 25%"></th>{% for mesa in mesas %}<th style="width: {{ anchocol }}%">{{ mesa.nombre }}</th>{% endfor %}</tr>
    {% for slot in slots %}
    <tr>
        <td style="width: 25%">{{ slot }}</td>
        {% for mesa in mesas %}<td style="width: {{ anchocol }}%">{{ reservas|keyvalue:slot.id|keyvalue:mesa.id }}</td>{% endfor %}
    </tr>
    {% endfor %}
</table>
<p class="fechahorasrv">Actualizado a {{ fechahoraactual|date:"G:i:s, j/n/Y" }}</p>
{% endblock content %}

pit/templates/pit/horario1080.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block metas %}
    <meta http-equiv="refresh" content="5">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
{% endblock metas %}

{% block bodytags %} class="horario1080"{% endblock %}

{% block content %}

<h1 class="horario1080">Reservas {{ nombresala }}</h1>
<table class="horariopublico">
    <tr><th style="width: 15%"></th>{% for mesa in mesas %}<th style="width: {{ anchocol }}%">{{ mesa.nombre }}</th>{% endfor %}</tr>
    {% for slot in slots %}
    <tr>
        <td style="width: 15%">{{ slot }}</td>
        {% for mesa in mesas %}<td style="width: {{ anchocol }}%">{{ reservas|keyvalue:slot.id|keyvalue:mesa.id }}</td>{% endfor %}
    </tr>
    {% endfor %}
</table>
<p class="fechahorasrv">Actualizado a {{ fechahoraactual|date:"G:i:s, j/n/Y" }}</p>
{% endblock content %}

pit/templates/pit/horariofuturocompleto.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block metas %}
    <meta http-equiv="refresh" content="5">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
{% endblock metas %}

{% block bodytags %}{% endblock %}

{% block content %}
<p><a href="{% url 'pit:index' %}">Volver atrás</a></p>
<h1>Reservas {{ nombresala }}</h1>
<table class="horariocompleto">
    <tr><th style="width: 25%"></th>{% for mesa in mesas %}<th style="width: {{ anchocol }}%">{{ mesa.nombre }}</th>{% endfor %}</tr>
    {% for slot in slots %}
    <tr>
        <td style="width: 25%">{{ slot }}</td>
        {% for mesa in mesas %}<td style="width: {{ anchocol }}%">{{ reservas|keyvalue:slot.id|keyvalue:mesa.id }}</td>{% endfor %}
    </tr>
    {% endfor %}
</table>
<p>Actualizado a {{ fechahoraactual|date:"G:i:s, j/n/Y" }}</p>
{% endblock content %}

pit/templates/pit/horariopasado.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block metas %}
    <meta http-equiv="refresh" content="5">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
{% endblock metas %}

{% block bodytags %}{% endblock %}

{% block content %}
<p><a href="{% url 'pit:index' %}">Volver atrás</a></p>
<h1>Reservas pasadas de {{ nombresala }}</h1>
<table class="horariocompleto">
    <tr><th style="width: 25%"></th>{% for mesa in mesas %}<th style="width: {{ anchocol }}%">{{ mesa.nombre }}</th>{% endfor %}</tr>
    {% for slot in slots %}
    <tr>
        <td style="width: 25%">{{ slot }}</td>
        {% for mesa in mesas %}<td style="width: {{ anchocol }}%">{{ reservas|keyvalue:slot.id|keyvalue:mesa.id }}</td>{% endfor %}
    </tr>
    {% endfor %}
</table>
<p>Actualizado a {{ fechahoraactual|date:"G:i:s, j/n/Y" }}</p>
{% endblock content %}

pit/templates/pit/horariostatic.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block metas %}
    <meta http-equiv="refresh" content="30">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
{% endblock metas %}

{% block bodytags %} class="horariostatic"{% endblock %}

{% block content %}

<div style="width: 90%; margin: auto; text-align: center">
    <h1 class="horariostatic">Reservas {{ nombresala }}</h1><img class="logo" alt="Cargo Connect" src="/static/logo-1140.png" />
</div>
{% if datos.salas|length > 1 %}
<p class="enlacesalas">Selecciona el PIT: <a href="/">Todos</a>, {% for sala in salas %}<a href="{{ sala.nombre|cut:' ' }}.html">{{ sala.nombre }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}.</p>
{% endif %}
<p class="avisopit">Web en fase beta. Puede que algún cambio no esté incluídos en este horario, acude al PIT para ver la información más reciente.</p>
<table class="horariopublico">
    <tr><th style="width: 15%"></th>{% for mesa in mesas %}<th style="width: {{ anchocol }}%">{{ mesa.nombre }}</th>{% endfor %}</tr>
    {% for slot in slots %}
    <tr>
        <td style="width: 15%">{{ slot }}</td>
        {% for mesa in mesas %}<td style="width: {{ anchocol }}%">{{ reservas|keyvalue:slot.id|keyvalue:mesa.id }}</td>{% endfor %}
    </tr>
    {% endfor %}
</table>
<p class="fechahorasrv">Actualizado a {{ fechahoraactual|date:"G:i:s, j/n/Y" }} - <a href="https://github.com/jariza/flldj">Source</a></p>
{% endblock content %}

pit/templates/pit/index.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block imports %}
{% endblock imports %}

{% block content %}

<h1>Control de reservas de PIT</h1>
<form action="{% url 'pit:actualizarhorario' %}" method="post">
    <p><label for="mesa">Mesa</label>:<br />
        <select id="mesa" name="mesa">
        {% for mesa in datos.mesas %}
        <option value="{{ mesa.id }}">{{ mesa.nombre }} ({{ mesa.sala }})</option>
        {% endfor %}
    </select></p>
    <p><label for="slot">Slot</label>:<br />
        <select id="slot" name="slot">
        {% for slot in datos.slots %}
        <option value="{{ slot.id }}">{{ slot.horainicio|date:'H:i' }}-{{ slot.horafin|date:'H:i' }}</option>
        {% endfor %}
    </select></p>
    <p><label for="equipo">Equipo</label>:<br />
        <select id="equipo" name="equipo">
        <option value="-1" selected>Liberar slot</option>
        {% for equipo in datos.equipos %}
        <option value="{{ equipo.id }}">{{ equipo.idequipo }} - {{ equipo.nombre }}</option>
        {% endfor %}
    </select></p>
    {% csrf_token %}
    <p><input type="submit" value="Actualizar"></p>
</form>

<p>Horarios completos:</p>
<ul>
{% if datos.salas|length > 1 %}
    <li><a href="horariocompleto/0/">Todas las mesas</a></li>
{% endif %}
{% for sala in datos.salas %}
    <li><a href="horariocompleto/{{ sala.id }}/">{{ sala.nombre }}</a></li>
{% endfor %}
</ul>

<p>Reservas pasadas:</p>
<ul>
{% if datos.salas|length > 1 %}
    <li><a href="horariopasado/0/">Todas las mesas</a></li>
{% endif %}
{% for sala in datos.salas %}
    <li><a href="horariopasado/{{ sala.id }}/">{{ sala.nombre }}</a></li>
{% endfor %}
</ul>

<p><a href="{% url 'pit:recursos' %}">Horarios públicos y recursos</a></p>
<p class="fechahorasrv">Fecha y hora del servidor: {{ datos.fechahoraservidor|date:"G:i:s, j/n/Y" }}</p>
{% endblock content %}

pit/templates/pit/recursos.html
{% extends "base.html" %}
{% load keyvalue %}

{% block title %}PIT{% endblock %}

{% block imports %}
{% endblock imports %}

{% block content %}

<h1>Horarios públicos y recursos</h1>
<p>Material extra:</p>
<ul>
    <li><a href="/static/wallpaper.jpg">Fondo de escritorio</a></li>
    <li><a href="https://support.mozilla.org/en-US/questions/1269565">Cómo quitar la caja de estado en Firefox</a></li>
{% for enlaceextra in enlacesextra %}
    <li><a href="{{ enlaceextra.enlace }}">{{ enlaceextra.texto }}</a></li>
{% endfor %}
</ul>
<p>Enlaces a horarios públicos:</p>
<ul>
{% if datos.salas|length > 1 %}
    <li><a href="{% url 'pit:horario' sala=0 %}">Todas las mesas</a></li>
{% endif %}
{% for sala in salas %}
    <li><a href="{% url 'pit:horario' sala=sala.id %}">{{ sala.nombre }}</a></li>
{% endfor %}
</ul>
<p>Enlaces a horarios públicos 1920x1080:</p>
<ul>
{% if datos.salas|length > 1 %}
    <li><a href="{% url 'pit:horario1080' sala=0 %}">Todas las mesas</a></li>
{% endif %}
{% for sala in salas %}
    <li><a href="{% url 'pit:horario1080' sala=sala.id %}">{{ sala.nombre }}</a></li>
{% endfor %}
</ul>
<p>Enlaces a horarios para web pública:</p>
<ul>
{% if datos.salas|length > 1 %}
    <li><a href="{% url 'pit:horariostatic' sala=0 %}">Todas las mesas</a></li>
{% endif %}
{% for sala in salas %}
    <li><a href="{% url 'pit:horariostatic' sala=sala.id %}">{{ sala.nombre }}</a></li>
{% endfor %}
</ul>

<p><a href="{% url 'pit:index' %}">Volver atrás</a></p>
{% endblock content %}